name: payze_plugin
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/MobileUdevs/payze_plugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: uz.udevs.payze_plugin
        pluginClass: PayzePlugin
      ios:
        pluginClass: PayzePlugin
